language: python

python:
- '3.6'
- '3.7'
- '3.8'

env:
  global:
  - secure: Dyl3SxYuLGgdaEdYmXapMwlvV499GB52t2HD6bFP+xzA4Yv7dUzBq4IkOCZMaJm1VceQMNJYFAUhFjvwBP5J6fr/6VQcSaAfPX/MDXJ7eO4Xhyza0gW4oVQcpG1PZEXO1oY7BspRlU7tsoqRddFneYwLZfxo4W3iZJF4QTlPSO+kbLB/M4udIxFK98ZpIMqQS2ThRC4qK5KGoqSr3IgD3XqjhLgrdrczr/LJAKwzNIJ1fnQAl0EtbbliA9zi0IP/zM/kEOcivJ3GHsiZjgzlc5bCGGJd7eMHK2rSKruXZR8PeLNfqgVGeJD0ZBnaY3v17Sqqk56uzVdSz0lOcLcFeJu9efrTENhjZGtFBnaTBJW5Gv7pvk5CRGCdpmRDaKMx8c4VtX8rMENy2YKA5/Q8N1DivuokhdBAndmTQJXEQLkFyQNIEhG8tUcLeBao67O+EYzAonFfZPiVZW0vQ7Vsun1xpErYgpZH/N8kU0iOvSpMi7U1YkAPYgIepyZnOPdyDaKwiYspjNQuYeovWxjcuGBd5FnGtdVk2p0zFiljn/o4gsOYu4QWVgPBq66reuJjJdW+mMVSCVp02MEYVDvpYnHHH8SS6jba5XJuJIbmEWWSUT/zUcwUgeX7BBdRw9vnGQP9aLLrudytXbHJG84O9FyX64ZDjpSrKRvEUwvGMA4=

install:
- pip install -r requirements.txt

script:
- make lint
- pytest --cov=smithnormalform

after_success:
- coveralls

notifications:
  email:
    on_success: never
    on_failure: always

jobs:
  include:
  - stage: deploy
    python: '3.8'
    if: tag IS present
    deploy:
      provider: pypi
      distributions: sdist bdist_wheel
      on:
        tags: true
      username: __token__
      password:
        secure: CYGZZS3GJVPH8w4Pq0t7TfimhmQLo89GNReHpzm8gUReQ7SrNj0N29Mjbfr7ZKeUoa/ndasbwxksLdtgsJi5rrGZV8daXUdY3J9vXfcju8ngN3JYwEGY4N02BitqWXEhLQtFm7DNK9M0xz2uwqo6gBK6255cSXknE8RJtOLkmxG9mcnmS2o/5xwvBiJ2isieCb1PMTwCu7cBTOWXT7gJXHtu9UgPjH3X0mrN56ksjECzT+fmZMrIYk6fbkP/uBa1LqRZe4Aqd2n+JBIiIem7GZMw/FjrPhZEGkEzIERZa5VuMrkuIsDwwzM9BhubbIS/SNSwqHuASI/I6C1eCXBz4bBLqSzOopxNHi0SF7WUFDr6XzBpSUSjxhYHnexxP5PEm4ej2aUVMW9Gm84ozod2nh11maoiv8Wz+Tzz7kT9Gp1YdVAqRVH+yw2Nt661HyLpleicABHpwFqXE9zg0cEQPSA4wgDwCkm5pdfjcTTan/iZ4AAp0fNWtJoKbBbSR6Ml/ztVGK0Hx33ftNU0HgGnO/AGJPIlXQBGF6Po7jufNrxGtWOMTKUzcA9fFxw/rru1mnl7P8bXJ0KKU6RVwa5s04p+frupKJ0F+cLaJt/pWR/vGinVflxQtL/ZVu4DNoafaOBw/fHH5wTK1VtxLQw1Zgdef1Ur6hZxPFK1q3MUjgE=
