language: python

python:
- '3.6'
- '3.7'
- '3.8'

install:
- pip install -r requirements.txt

script:
- make test
- make lint

deploy:
  provider: script
  script: echo "hello world"
  on:
    tags: true
    python: '3.8'
