language: python

python:
- '3.6'
- '3.7'
- '3.8'

install:
- pip install -r requirements.txt

script:
- make test
- make lint

jobs:
  include:
    - stage: build
      python: 3.6
      script: echo deploy
     

