language: python

python:
- '3.6'
- '3.7'
- '3.8'

install:
- pip install -r requirements.txt

script:
- make test
- make lint

jobs:
    include:
        - stage: deploy
              python: 3.8
              if: tag IS present
              build:
                  provider: script
                  script: echo "this is a deploy"
